import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "프로젝트",
  description: "Generated by create next app",
};

export default function ProjectsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col items-center">
      <header className="w-full max-w-6xl mx-auto py-8 text-center">
        <h1 className="text-5xl font-black mb-4">
          KUSITMS의 다양한 프로젝트를 <br />
          구경해보세요!
        </h1>
        <p className="font-normal text-[20px]">
          <span className="text-[#62EFE5]">45개</span>의 프로젝트를 볼 수
          있어요.
        </p>
        <div className="flex gap-4 justify-center">
          <Link href="/projects/meetup">
            <button
              className="flex cursor-pointer rounded-[75px] border-0 mx-[16px] 
            mt-[48px] h-[53px] px-[32px] justify-center 
            items-center bg-[#2f3038] font-bold"
            >
              밋업데이
            </button>
          </Link>
          <Link href="/projects/enterprise">
            <button
              className="flex cursor-pointer rounded-[75px] border-0 mx-[16px] mt-[48px] 
            h-[53px] px-[32px] justify-center items-center bg-[#2f3038] font-bold"
            >
              기업 프로젝트
            </button>
          </Link>
        </div>
      </header>
      <main className="w-full max-w-6xl mx-auto">{children}</main>
    </div>
  );
}
