import Image from "next/image";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import { PageNav } from "@/components/shared";
import type { Metadata } from "next";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "KUSITMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-full px-12 py-6">
          <div className="max-w-[2000px] w-full mx-auto flex justify-between">
            <Link href="/">
              <Image
                src="/headerLogo.svg"
                alt="큐시즘 로고"
                width={142}
                height={26}
                priority
              />
            </Link>

            <PageNav />
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
